INT_PORT: 8080
REST_PORT: 8080
JWT_SECRET: 2G7Rnnvt6KCN2gmX2GCU106YOiOJA2fgp3hg2jL5UDA=

USER_POSTGRES:
  POSTGRES_HOST: postgresql_users
  POSTGRES_PORT: 5432
  POSTGRES_USER: users_pgs_user
  POSTGRES_PASSWORD: 1234
  POSTGRES_DB: users
  POSTGRES_MAX_CONN: 10
  POSTGRES_MIN_CONN: 1