// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: user.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *SignUpResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type FillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ege           int32                  `protobuf:"varint,1,opt,name=ege,proto3" json:"ege,omitempty"`
	Gpa           int32                  `protobuf:"varint,2,opt,name=gpa,proto3" json:"gpa,omitempty"`
	Speciality    string                 `protobuf:"bytes,3,opt,name=speciality,proto3" json:"speciality,omitempty"`
	EduType       string                 `protobuf:"bytes,4,opt,name=eduType,proto3" json:"eduType,omitempty"`
	Town          string                 `protobuf:"bytes,5,opt,name=town,proto3" json:"town,omitempty"`
	Financing     string                 `protobuf:"bytes,6,opt,name=financing,proto3" json:"financing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillRequest) Reset() {
	*x = FillRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillRequest) ProtoMessage() {}

func (x *FillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillRequest.ProtoReflect.Descriptor instead.
func (*FillRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *FillRequest) GetEge() int32 {
	if x != nil {
		return x.Ege
	}
	return 0
}

func (x *FillRequest) GetGpa() int32 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *FillRequest) GetSpeciality() string {
	if x != nil {
		return x.Speciality
	}
	return ""
}

func (x *FillRequest) GetEduType() string {
	if x != nil {
		return x.EduType
	}
	return ""
}

func (x *FillRequest) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *FillRequest) GetFinancing() string {
	if x != nil {
		return x.Financing
	}
	return ""
}

type FillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillResponse) Reset() {
	*x = FillResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillResponse) ProtoMessage() {}

func (x *FillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillResponse.ProtoReflect.Descriptor instead.
func (*FillResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *FillResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type EditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ege           int32                  `protobuf:"varint,1,opt,name=ege,proto3" json:"ege,omitempty"`
	Gpa           int32                  `protobuf:"varint,2,opt,name=gpa,proto3" json:"gpa,omitempty"`
	Speciality    string                 `protobuf:"bytes,3,opt,name=speciality,proto3" json:"speciality,omitempty"`
	EduType       string                 `protobuf:"bytes,4,opt,name=eduType,proto3" json:"eduType,omitempty"`
	Town          string                 `protobuf:"bytes,5,opt,name=town,proto3" json:"town,omitempty"`
	Financing     string                 `protobuf:"bytes,6,opt,name=financing,proto3" json:"financing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditRequest) Reset() {
	*x = EditRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditRequest) ProtoMessage() {}

func (x *EditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditRequest.ProtoReflect.Descriptor instead.
func (*EditRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *EditRequest) GetEge() int32 {
	if x != nil {
		return x.Ege
	}
	return 0
}

func (x *EditRequest) GetGpa() int32 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *EditRequest) GetSpeciality() string {
	if x != nil {
		return x.Speciality
	}
	return ""
}

func (x *EditRequest) GetEduType() string {
	if x != nil {
		return x.EduType
	}
	return ""
}

func (x *EditRequest) GetTown() string {
	if x != nil {
		return x.Town
	}
	return ""
}

func (x *EditRequest) GetFinancing() string {
	if x != nil {
		return x.Financing
	}
	return ""
}

type EditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditResponse) Reset() {
	*x = EditResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditResponse) ProtoMessage() {}

func (x *EditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditResponse.ProtoReflect.Descriptor instead.
func (*EditResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *EditResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\"A\n" +
	"\rSignUpRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"(\n" +
	"\x0eSignUpResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"'\n" +
	"\rLoginResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\x9d\x01\n" +
	"\vFillRequest\x12\x10\n" +
	"\x03ege\x18\x01 \x01(\x05R\x03ege\x12\x10\n" +
	"\x03gpa\x18\x02 \x01(\x05R\x03gpa\x12\x1e\n" +
	"\n" +
	"speciality\x18\x03 \x01(\tR\n" +
	"speciality\x12\x18\n" +
	"\aeduType\x18\x04 \x01(\tR\aeduType\x12\x12\n" +
	"\x04town\x18\x05 \x01(\tR\x04town\x12\x1c\n" +
	"\tfinancing\x18\x06 \x01(\tR\tfinancing\"&\n" +
	"\fFillResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\x9d\x01\n" +
	"\vEditRequest\x12\x10\n" +
	"\x03ege\x18\x01 \x01(\x05R\x03ege\x12\x10\n" +
	"\x03gpa\x18\x02 \x01(\x05R\x03gpa\x12\x1e\n" +
	"\n" +
	"speciality\x18\x03 \x01(\tR\n" +
	"speciality\x12\x18\n" +
	"\aeduType\x18\x04 \x01(\tR\aeduType\x12\x12\n" +
	"\x04town\x18\x05 \x01(\tR\x04town\x12\x1c\n" +
	"\tfinancing\x18\x06 \x01(\tR\tfinancing\"&\n" +
	"\fEditResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status2\xb9\x02\n" +
	"\vUserService\x12N\n" +
	"\x06SignUp\x12\x12.api.SignUpRequest\x1a\x13.api.SignUpResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/user/signup\x12J\n" +
	"\x05Login\x12\x11.api.LoginRequest\x1a\x12.api.LoginResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/user/login\x12F\n" +
	"\x04Fill\x12\x10.api.FillRequest\x1a\x11.api.FillResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/user/fill\x12F\n" +
	"\x04Edit\x12\x10.api.EditRequest\x1a\x11.api.EditResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/user/editB\x11Z\x0fbackend/pkg/apib\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_proto_goTypes = []any{
	(*SignUpRequest)(nil),  // 0: api.SignUpRequest
	(*SignUpResponse)(nil), // 1: api.SignUpResponse
	(*LoginRequest)(nil),   // 2: api.LoginRequest
	(*LoginResponse)(nil),  // 3: api.LoginResponse
	(*FillRequest)(nil),    // 4: api.FillRequest
	(*FillResponse)(nil),   // 5: api.FillResponse
	(*EditRequest)(nil),    // 6: api.EditRequest
	(*EditResponse)(nil),   // 7: api.EditResponse
}
var file_user_proto_depIdxs = []int32{
	0, // 0: api.UserService.SignUp:input_type -> api.SignUpRequest
	2, // 1: api.UserService.Login:input_type -> api.LoginRequest
	4, // 2: api.UserService.Fill:input_type -> api.FillRequest
	6, // 3: api.UserService.Edit:input_type -> api.EditRequest
	1, // 4: api.UserService.SignUp:output_type -> api.SignUpResponse
	3, // 5: api.UserService.Login:output_type -> api.LoginResponse
	5, // 6: api.UserService.Fill:output_type -> api.FillResponse
	7, // 7: api.UserService.Edit:output_type -> api.EditResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
