services:
  postgresql_users:
    container_name: users_postgres_service
    image: postgres:latest
    env_file:
      - ../env/users_postgres.env
    ports:
      - "${INT_PORT}:${REST_PORT}"
    volumes:
      - ../database_data/users_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U users_pgs_user -d users -p 5432"  ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network


  postgresql_integration:
    container_name: integration_postgres_service
    image: postgres:latest
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: int_pgs_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: integration
      POSTGRES_MAX_CONN: 10
      POSTGRES_MIN_CONN: 1
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5433"
    volumes:
      - ../backend/database_data/integration_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U int_pgs_user -d integration -p 5433"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  user_service:
    container_name: user_service
    build:
      context: ../
      dockerfile: ../backend/cmd/user/Dockerfile
    env_file:
      - ../env/users_postgres.env
      - ../env/user.env
    ports:
      - "${INT_USER_PORT}:${REST_USER_PORT}"
    networks:
      - app_network
    restart: unless-stopped
    depends_on:
      postgresql_users:
        condition: service_healthy

networks:
  app_network:
    driver: bridge